//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisAPIAndScrappingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrandSlamInfo
    {
        public int Id { get; set; }
        public string Year { get; set; }
        public string UsOpen { get; set; }
        public string AustralianOpen { get; set; }
        public string RolandGarros { get; set; }
        public string Wimbledon { get; set; }
        public Nullable<int> PlayerId { get; set; }
    }
}
