//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisAPIAndScrappingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Matches()
        {
            this.MatchScores = new HashSet<MatchScores>();
        }
    
        public decimal MatchId { get; set; }
        public int ContestGroupId { get; set; }
        public Nullable<int> ContestGroupRoundId { get; set; }
        public short MatchStatusId { get; set; }
        public System.DateTime MatchDate { get; set; }
        public bool IsLive { get; set; }
        public bool Lights { get; set; }
        public string HomeTeamShirt { get; set; }
        public string AwayTeamShirt { get; set; }
        public Nullable<short> CurrentMinutes { get; set; }
        public Nullable<System.DateTime> MatchStartTime { get; set; }
        public Nullable<System.DateTime> FirstHalfEndTime { get; set; }
        public Nullable<short> MinuteDifference { get; set; }
        public Nullable<bool> MinutePlusBit { get; set; }
        public string FirstToServe { get; set; }
        public string SportCCMatchId { get; set; }
        public Nullable<System.DateTime> LastUpdatedTime { get; set; }
        public Nullable<bool> IsLeagueTableUpdated { get; set; }
        public Nullable<System.Guid> AssignedByUserId { get; set; }
        public string AssignedByUserName { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.Guid> AssignedToUserId { get; set; }
        public Nullable<System.DateTime> SportingLifeMatchDate { get; set; }
        public string CrawlerLink { get; set; }
        public Nullable<bool> AutoCrawl { get; set; }
        public string CreatedByRole { get; set; }
        public Nullable<long> ProviderMatchId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> SharkScoresMatchId { get; set; }
        public Nullable<int> CrawlFrom { get; set; }
        public Nullable<int> SportingbetMatchId { get; set; }
        public Nullable<int> LiveScoreMatchId { get; set; }
        public byte[] change_stamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchScores> MatchScores { get; set; }
    }
}
