//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisAPIAndScrappingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerOverview
    {
        public int Id { get; set; }
        public Nullable<int> CareerSingleTitle { get; set; }
        public Nullable<int> CareerMatchesWon { get; set; }
        public Nullable<int> YTDMatchWon { get; set; }
        public Nullable<int> CareerDoublesTitle { get; set; }
        public Nullable<int> CareerMatchesLost { get; set; }
        public Nullable<int> YTDMatchesLost { get; set; }
        public Nullable<int> WeekRankSingle { get; set; }
        public Nullable<int> HighRankSingle { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string YTDServiceGamesWon { get; set; }
        public string YTDReturnGamesWon { get; set; }
    }
}
