//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisAPIAndScrappingService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RankingPlayersProfiles
    {
        public int Id { get; set; }
        public Nullable<int> Move { get; set; }
        public string MoveType { get; set; }
        public Nullable<int> Ranking { get; set; }
        public string Country { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<int> TournPlayed { get; set; }
        public Nullable<int> PointDropping { get; set; }
        public Nullable<int> NextBest { get; set; }
        public Nullable<int> SportCCPlayerId { get; set; }
        public string AtpId { get; set; }
        public string PlayerLink { get; set; }
        public string CoachName { get; set; }
        public string Residence { get; set; }
        public string PlayerPosition { get; set; }
        public string TurnPro { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> WtaTId { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string Type { get; set; }
    }
}
